version: '3.4'

services:
  timekeeperfaceserver:
    image: timekeeperfaceserver
    build: '.'
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - 5000:5000
    env_file:
      - ./.env.production
    networks:
      - default
    depends_on:
      - database
  database:
    image: postgres:14.3-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=170101
      - POSTGRES_DB=hcmus
      - POSTGRES_HOST=localhost
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
volumes:
    postgres_data:
networks:
  default:
    name: postgre-service_default
